# URL's of the various nre-feeds API's
services:
  reference: https://ref.prod.a51.li
  ldb: https://ldb.prod.a51.li

# TLS details, only needed when using telnet-ssl
tls:
# Certificate path
#  cert: /path/to/ssl-cert-snakeoil.pem
# Private key
#  key: /path/to/ssl-cert-snakeoil.key

shell:
  # Command prompt
  prompt: ">"
  # Message sent on initial login
  welcomeMessage: "\r\n\nWelcome to departureboards.mobi\r\n\n"
  # Message sent on logoff
  exitMessage: "Goodbye\r\n\n"

# List of telnet ports to open
telnet:
  - # Shell for humans
    # The port to listen to
    port: 8081
    # true use telnet-ssl or plain telnet
    secure: false
    shell:
      prompt: ">"
      welcomeMessage: "\n\nWelcome to departureboards.mobi\n"
      exitMessage: "Goodbye\n"
  - # Shell for computers
    port: 8082
    secure: false
    api: true
    shell:
      prompt: ""
      welcomeMessage: "Welcome to departureboards.mobi"
      exitMessage: "Goodbye"
